### ISSUE TITLE
Measure embedding model?

### ISSUE THREAD

**Issue by JulianSlzr** [OMR-Research/MeasureDetector#11]
Thanks for this efficient and effective measure detection model!

My collaborator and I were wondering if the trained embedding model could be shared as-is (section 4.2 of https://publik.tuwien.ac.at/files/publik_282966.pdf) either here or directly. If not, pointers to the 81k measure annotations (section 3) would help us train our own; https://github.com/apacha/OMR-Datasets#muscima-measure-annotations only gives 2.8k system measure annotations.

(**Context:** we've developed a low-resource neural alignment method and hope to apply it to audio-measure alignment, a task done manually in https://ismir2022program.ismir.net/lbd_399.html. Our method works best with semantic feature embeddings.)

Let us know!

**Comment by sonovice** [comment]
Nice paper!

The trained model can be downloaded here: https://github.com/OMR-Research/MeasureDetector/releases/download/v1.0/2019-05-16_faster-rcnn-inception-resnet-v2.pb

The detector is based on Faster R-CNN and does not expose the embeddings in a ready-to-use way. However, take a look at https://github.com/cemfi/measure-detector/blob/dee203d99d68efb050faf2aa40efb618f8520526/backend/server.py#L62 for a way to get intermediate tensors from a TF graph.
I looked through the model using www.netron.app - You might have luck using the output of `SecondStageFeatureExtractor/InceptionResnetV2/Conv2d_7b_1x1/Relu` as an embedding for the entire image. This should be the last layer before feature post processing and box prediction.
If you want individual measure embeddings, you could try `SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/map/TensorArray_7` but I am not sure if this would help you that much since the second stage in Faster R-CNN does not really provide "semantic" features but rather simple classification inputs.

However, I have an yet unpublished model that might be a good fit for your use case since it is trained with the goal to distinguish between different measures per their distance in embedding space. Feel free to contact me directly at waloschek@pm.me

**Comment by JulianSlzr** [comment]
Your thoughts on the detector followed ours. I'd downloaded the TF graph and extracted pooled RoI embeddings per bounding box. However, we also noted that while the objective may induce detection of bar lines and clusters of stems, it's unlikely to learn semantics (notes, rhythms). We've also considered other OMR featurizers (e.g., https://github.com/BreezeWhite/oemer), but an explicitly trained embedding model is best.

I've e-mailed you. Thanks in advance!
