### ISSUE TITLE
Provide a demo for the stave detector

### ISSUE THREAD

**Issue by piegamesde** [OMR-Research/MeasureDetector#4]
I'm not very familiar with machine learning, so I haven't managed to successfully train any models myself. But the provided model from the demo works fine, and I'm using that for a while now.

However, I'm finding myself in the need of proper staff detection. I managed to work around this for a while by merging the detected bars, but it ultimately has some limits. I'd thus really appreciate it if you provided a trained model for this as well.

**Comment by apacha** [comment]
Hi,
thanks for the interest. If I understand you correctly, you want staff detection instead of measure detection, right? How about checking out the work from my student Marc Kletz, who worked on this problem and released several models that are specially trained to detect staves, measures and system measures: https://github.com/MarcKletz/OMR-MeasureRecognition

Let me know if that helps. Before you invest a lot of time into setting it up, you can try the demo online: https://share.streamlit.io/marckletz/omr-measurerecognition/Python/streamlit_app.py

**Comment by piegamesde** [comment]
Thanks for linking that project. It looks really cool, and finding things on GitHub is really hard as the results are drowned in failed attempts and other useless toy experiments. And the online demo is indeed incredibly convenient.

It seems to only detect the staff lines and not the bounding box of the whole staff system (which is what I need in the end), but I should be able to get it working with some simple post processing.

If you have a pre-trained model for this project's `StaveDetector` lying around I'll still appreciate that, if only to have a look at which one of these options gets me closer to what I need.

**Comment by apacha** [comment]
If you want the staff system, make sure that you select the right category in the drop-down on the left. There are different models for just staff, measure or system measure, including models that combine all three things.

I noticed, that the demo seems to have crashed, but it's hopefully back and running again in no time.

**Comment by piegamesde** [comment]
> It seems to only detect the staff lines and not the bounding box of the whole staff system (which is what I need in the end)

No, what I meant was the bounds not only containing the staff lines, but also all music annotations that go with it. But again, that is only a nice-to-have as I should be able to implement parts of https://dl.acm.org/doi/pdf/10.1145/3103010.3103012 after the detection to get what I need.
